#pragma once
#define MODELS__
#include "Hero.h"
#include "Block.h"
#include "Coin.h"
#include "Obstacle.h"
#include "PowerUp.h"
#include "Spaceship.h"
#include "Spike.h"
#include "Villian.h"
#include "WoodenBox.h"
#include "FireBlock.h"
#include "SmartEnemy.h"
#include "NextLevelPortal.h"